### ISSUE TITLE
想请教一下这个是怎么做到的，只能这么发问了不好意思😂

### ISSUE THREAD

**Issue by Panway** [daodaolee/typora-scrolls#1]
![image](https://user-images.githubusercontent.com/12131567/112595878-fe950a00-8e45-11eb-8a1d-d9910fa03d5b.png)

**Comment by daodaolee** [comment]
你说的是这个目录么？这个应该是github自己的吧，之前没有，我记得TOC也不好使，应该是官方自己弄的，方便阅读 @Panway

**Comment by Panway** [comment]
对的，github改版了，当时我试了下只有你的仓库有目录，我还以为你的md格式有啥特殊的呢
